version: "3.9"
services:
  postgres:
    image: postgres
    ports:
      - "8081:5432"
    environment:
      POSTGRES_DB: stocks-client
      POSTGRES_USER: stocks-client
      POSTGRES_PASSWORD: stocks-client

