version: "3.9"
services:
  postgres:
    image: postgres
    ports:
      - "8083:5432"
    environment:
      POSTGRES_DB: stocks-server
      POSTGRES_USER: stocks-server
      POSTGRES_PASSWORD: stocks-server

